### ISSUE TITLE
可以进一步简化

### ISSUE THREAD

**Issue by charles9056** [a-wing/Github-dashboard#1]
实际上可以删掉第9行和第11行，然后把第10行顶格书写。这样就看起来更简单了：）
https://github.com/a-wing/Github-dashboard/blob/c957409641257ca2d8c25f59cc8b80b244da3c7b/github-dashboard.user.js#L9
https://github.com/a-wing/Github-dashboard/blob/c957409641257ca2d8c25f59cc8b80b244da3c7b/github-dashboard.user.js#L11
最终效果：
```
// ==UserScript==
// @name     				Github dashboard sidebar right
// @author          a-wing
// @version  				1
// @grant    				none
// @include         https://github.com/
// ==/UserScript==
document.getElementsByClassName("dashboard-sidebar")[0].style.cssFloat= "right"
```

**Comment by a-wing** [comment]
是可以这样简化。也能运行。。。。我对JavaScript理解没有那样深入。主要是大家都这样写闭包。。。。简化之后我不清处会不会有潜在问题（应该没有吧，毕竟没用变量）。。求教QAQ

**Comment by seanhuai** [comment]
闭包主要是顾及到全局变量污染，这里没有问题的...
